@echo off

SET PATH=%IBMCDIR%\bin;%BASEPATH%
SET COMP=IC
SET LINK=IL
SET WCC=/d2/w4/zq/zp1/d__WCVER__#%WCVER%
SET INCLUDE=%IBMCDIR%\include;%TOOLKT20INC%;%stdinclude%
SET LIB=%DEVROOT%slib;%IBMCDIR%\lib;%TOOLKT20LIB%
